---
- name: My dev setup
  hosts: localhost
  tasks:

  - name: Set package list
    set_fact:
      packages:
        - git
        - tmux
        - fish
        - curl
        - rust
        - rustc
      state: latest

  - name: Install packages
    become: yes
    package:
      name: "{{ packages }}"
      state: present

  - name: installing requirement tools linux
    tags:
      - neovim
      - fish
    become: yes
    vars:
      macos_dependencies:
        - ninja
        - libtool
        - cmake
        - pkg-config
        - gettext
        - curl
        - python3-pip
        - curl-ca-bundle  # Only needed for older macOS versions
      ubuntu_dependencies:
        - ninja-build
        - gettext
        - libtool-bin
        - cmake
        - g++
        - pkg-config
        - unzip
        - curl
        - python3-pip
    apt:
      name: "{{ ubuntu_dependencies }}"
      state: present
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

  - name: installing tools for macos
    tags:
      - neovim
    become: yes
    vars:
      homebrew_packages:
        - ninja
        - libtool
        - cmake
        - pkg-config
        - gettext
        - curl
        - brew
        - python3-pip
        - curl-ca-bundle  # Only needed for older macOS versions
    homebrew:
      name: "{{ homebrew_packages }}"
      state: present
    when: ansible_distribution == 'MacOSX' and ansible_distribution_version.major >= 10


  - name: installing fish
    ansible.builtin.git:
      repo: 'https://github.com/fish-shell/fish-shell.git'
      dest: "~/fish-shell"
    tags:
      - fish

  - name: building fish
    shell: >
      cd ~/fish-shell; cmake .; make; sudo make install
    tags:
      - fish

  - name: Cloning .dotfiles
    ansible.builtin.git:
      repo: 'https://github.com/G33KM44N38/dotfiles'
      dest: "~/.config"
      recursive: yes
      update: yes
      version: main
      tags:
        - neovim
        - dotfiles

  - name: cloning neovim
    ansible.builtin.git:
      repo: 'https://github.com/neovim/neovim'
      dest: "~/neovim"
    tags:
      - neovim

  - name: installing vim-plug
    shell: >
      sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs \
       https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

  - name: building neovim
    shell: >
      cd ~/neovim && git checkout stable && make CMAKE_BUILD_TYPE=RelWithDebInfo && sudo make install && cd ~/ && rm -rf neovim \
      pip3 install pynvim
    tags:
      - neovim

  - name: installing tmux if macos
    shell: >
       brew install tmux
    when: ansible_distribution == 'MacOSX' and ansible_distribution_version.major >= 10
