---
- name: My dev setup
  hosts: localhost
  tasks:

  - name: installing requirement tools linux
    become: yes
    vars:
      macos_dependencies:
        - ninja
        - libtool
        - cmake
        - pkg-config
        - gettext
        - curl
        - curl-ca-bundle  # Only needed for older macOS versions
      ubuntu_dependencies:
        - ninja-build
        - gettext
        - libtool-bin
        - cmake
        - g++
        - pkg-config
        - unzip
        - curl
    apt:
      name: "{{ ubuntu_dependencies }}"
      state: present
    when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

  - name: installing tools for macos
    become: yes
    vars:
      homebrew_packages:
        - ninja
        - libtool
        - cmake
        - pkg-config
        - gettext
        - curl
        - neovim
        - brew
        - curl-ca-bundle  # Only needed for older macOS versions
    homebrew:
      name: "{{ homebrew_packages }}"
      state: present
    when: ansible_distribution == 'MacOSX' and ansible_distribution_version.major >= 10

  - name: Install Rust and Rustc
    hosts: all
    tasks:
      - name: Download Rust installer
        get_url:
          url: "https://static.rust-lang.org/rustup/dist/{{ ansible_system | lower }}/{{ ansible_architecture }}/rustup-init"
          dest: "/tmp/rustup-init"
          mode: '0755'
        become: yes
        when: ansible_system != 'Windows'

      - name: Install Rust on Linux and macOS
        command: "/tmp/rustup-init -y"
        args:
          creates: "/usr/local/bin/rustc"
        become: yes
        when: ansible_system != 'Windows'

      - name: Install Rust on Windows
        win_shell: "C:/Users/{{ ansible_user }}/AppData/Local/Temp/rustup-init.exe /S"
        args:
          creates: "C:/Program Files/Rust/bin/rustc.exe"
        when: ansible_system == 'Windows'

  - name: installing fish
    ansible.builtin.git:
      repo: 'https://github.com/fish-shell/fish-shell.git'
      dest: "~/fish-shell"

  - name: building fish
    shell: >
      cd ~/fish-shell; cmake .; make; sudo make install

  - name: Cloning .dotfiles
    ansible.builtin.git:
      repo: 'https://github.com/G33KM44N38/dotfiles'
      dest: "~/.config"
      recursive: yes
      update: yes
      version: master
      tags:
        - dotfiles

  - name: installing neovim
    ansible.builtin.git:
      repo: 'https://github.com/neovim/neovim'
      dest: "~/"

  - name: building neovim
    shell: >
      cd ~/neovim && git checkout stable && make CMAKE_BUILD_TYPE=RelWithDebInfo && sudo make install && cd ~/ && rm -rf neovim/

  - name: installing tmux if macos
    shell: >
       brew install tmux
    when: ansible_distribution == 'MacOSX' and ansible_distribution_version.major >= 10
